<?php
/**
 * Install WordPress API Handler
 * WordPress Hosting Panel with LiteSpeed
 */

/**
 * Install WordPress on a domain
 * 
 * @param array $body Request body containing installation parameters
 * @return array Installation result
 */
function install_wordpress($body) {
    // Validate request body
    if (!$body || !isset($body['domain_id']) || !isset($body['admin_email'])) {
        api_error('Domain ID and admin email are required');
    }
    
    $domain_id = (int)$body['domain_id'];
    $admin_email = filter_var($body['admin_email'], FILTER_VALIDATE_EMAIL);
    
    if (!$admin_email) {
        api_error('Invalid admin email address');
    }
    
    $db = Database::getInstance();
    $user = $_REQUEST['api_user'];
    
    // Get domain information
    if ($user['role'] === 'admin') {
        $domain = $db->fetchOne(
            "SELECT * FROM domains WHERE id = ?",
            [$domain_id]
        );
    } else {
        $domain = $db->fetchOne(
            "SELECT * FROM domains WHERE id = ? AND user_id = ?",
            [$domain_id, $user['id']]
        );
    }
    
    if (!$domain) {
        api_error('Domain not found or access denied', 404);
    }
    
    // Check if domain is active
    if ($domain['status'] !== 'active') {
        api_error('Domain must be active to install WordPress', 400);
    }
    
    // Check if WordPress is already installed
    $existing = $db->fetchOne(
        "SELECT id FROM wordpress_sites WHERE domain_id = ?",
        [$domain_id]
    );
    
    if ($existing) {
        api_error('WordPress is already installed on this domain', 409);
    }
    
    // Generate database credentials
    $db_name = 'wp_' . preg_replace('/[^a-z0-9]/', '_', strtolower($domain['domain_name']));
    $db_user = 'wp_' . substr(md5($domain['domain_name'] . time()), 0, 8);
    $db_password = bin2hex(random_bytes(8));
    
    // Set WordPress admin username
    $wp_admin_user = isset($body['admin_username']) ? $body['admin_username'] : 'admin';
    
    // Set WordPress admin password
    $wp_admin_password = isset($body['admin_password']) ? 
                         $body['admin_password'] : 
                         bin2hex(random_bytes(8));
    
    // Set WordPress site title
    $wp_title = isset($body['site_title']) ? 
                $body['site_title'] : 
                $domain['domain_name'];
    
    try {
        // Begin transaction
        $db->beginTransaction();
        
        // Insert WordPress site record
        $wp_id = $db->insert(
            "INSERT INTO wordpress_sites (domain_id, db_name, db_user, db_password, admin_email, status, installed_at) 
             VALUES (?, ?, ?, ?, ?, 'active', NOW())",
            [$domain_id, $db_name, $db_user, $db_password, $admin_email]
        );
        
        // Update domain record
        $db->update(
            "UPDATE domains SET updated_at = NOW() WHERE id = ?",
            [$domain_id]
        );
        
        // Create database and user
        $db->query("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $db->query("CREATE USER '$db_user'@'localhost' IDENTIFIED BY '$db_password'");
        $db->query("GRANT ALL PRIVILEGES ON `$db_name`.* TO '$db_user'@'localhost'");
        $db->query("FLUSH PRIVILEGES");
        
        // Download and extract WordPress
        $document_root = $domain['document_root'] . '/html';
        
        // Clear existing files
        if (file_exists($document_root)) {
            exec('rm -rf ' . escapeshellarg($document_root));
        }
        
        // Create document root
        mkdir($document_root, 0755, true);
        
        // Download WordPress
        exec('wget -q -O ' . escapeshellarg($document_root . '/wordpress.tar.gz') . ' ' . WP_DOWNLOAD_URL);
        exec('tar -xzf ' . escapeshellarg($document_root . '/wordpress.tar.gz') . ' -C ' . escapeshellarg($document_root));
        exec('mv ' . escapeshellarg($document_root . '/wordpress/*') . ' ' . escapeshellarg($document_root));
        exec('rm -rf ' . escapeshellarg($document_root . '/wordpress'));
        exec('rm ' . escapeshellarg($document_root . '/wordpress.tar.gz'));
        
        // Create wp-config.php
        $salts = file_get_contents('https://api.wordpress.org/secret-key/1.1/salt/');
        $config_content = "<?php
/**
 * WordPress Configuration File
 * Generated by WordPress Hosting Panel with LiteSpeed
 */

// Database settings
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASSWORD', '$db_password');
define('DB_HOST', 'localhost');
define('DB_CHARSET', 'utf8mb4');
define('DB_COLLATE', '');

// Authentication keys and salts
$salts

// Table prefix
\$table_prefix = 'wp_';

// Debug settings
define('WP_DEBUG', false);
define('WP_DEBUG_LOG', false);
define('WP_DEBUG_DISPLAY', false);

// Performance settings
define('WP_CACHE', true);
define('DISABLE_WP_CRON', false);
define('EMPTY_TRASH_DAYS', 7);
define('WP_MEMORY_LIMIT', '256M');
define('WP_MAX_MEMORY_LIMIT', '512M');

// Security settings
define('DISALLOW_FILE_EDIT', true);
define('AUTOMATIC_UPDATER_DISABLED', false);
define('WP_AUTO_UPDATE_CORE', 'minor');
define('FS_METHOD', 'direct');

// Absolute path to the WordPress directory
if (!defined('ABSPATH')) {
    define('ABSPATH', dirname(__FILE__) . '/');
}

// Sets up WordPress vars and included files
require_once(ABSPATH . 'wp-settings.php');";
        
        file_put_contents($document_root . '/wp-config.php', $config_content);
        
        // Set proper permissions
        exec('chown -R www-data:www-data ' . escapeshellarg($document_root));
        exec('chmod -R 755 ' . escapeshellarg($document_root));
        exec('find ' . escapeshellarg($document_root) . ' -type f -exec chmod 644 {} \\;');
        
        // Install WordPress using WP-CLI if available, otherwise use the web installer
        $wp_cli_available = exec('which wp') !== '';
        
        if ($wp_cli_available) {
            // Use WP-CLI for installation
            $wp_cmd = "cd $document_root && wp core install" .
                      " --url=http://{$domain['domain_name']}" .
                      " --title=" . escapeshellarg($wp_title) .
                      " --admin_user=" . escapeshellarg($wp_admin_user) .
                      " --admin_password=" . escapeshellarg($wp_admin_password) .
                      " --admin_email=" . escapeshellarg($admin_email) .
                      " --skip-email";
            
            exec($wp_cmd, $output, $return_var);
            
            if ($return_var !== 0) {
                throw new Exception("WP-CLI installation failed: " . implode("\n", $output));
            }
            
            // Install default plugins
            foreach (WP_DEFAULT_PLUGINS as $plugin => $url) {
                exec("cd $document_root && wp plugin install $plugin --activate", $plugin_output, $plugin_return);
            }
        } else {
            // Create a flag file for the web installer to pick up
            $install_data = [
                'title' => $wp_title,
                'admin_user' => $wp_admin_user,
                'admin_password' => $wp_admin_password,
                'admin_email' => $admin_email
            ];
            
            file_put_contents($document_root . '/.wp-install-data', json_encode($install_data));
            
            // Create an installer script that will run on first visit
            $installer_script = "<?php
// WordPress Auto-Installer
// This file will be deleted after installation

// Check if WordPress is already installed
if (file_exists('./wp-config.php') && !file_exists('./.wp-install-data')) {
    // Redirect to the WordPress site
    header('Location: /');
    exit;
}

// Load installation data
\$install_data = json_decode(file_get_contents('./.wp-install-data'), true);

if (!\$install_data) {
    die('Installation data not found');
}

// Set up the WordPress database
require_once('./wp-admin/includes/upgrade.php');
require_once('./wp-includes/wp-db.php');
require_once('./wp-includes/functions.php');
require_once('./wp-includes/load.php');
require_once('./wp-includes/plugin.php');
require_once('./wp-includes/kses.php');
require_once('./wp-includes/l10n.php');
require_once('./wp-includes/class-wp-locale.php');
require_once('./wp-includes/class-wp-locale-switcher.php');
require_once('./wp-admin/includes/schema.php');

// Create database tables
wp_install(
    \$install_data['title'],
    \$install_data['admin_user'],
    \$install_data['admin_email'],
    1, // public
    '', // deprecated
    \$install_data['admin_password']
);

// Delete the installation data and this file
@unlink('./.wp-install-data');
@unlink(__FILE__);

// Redirect to the WordPress admin
header('Location: /wp-admin/');
exit;
";
            
            file_put_contents($document_root . '/wp-install.php', $installer_script);
            
            // Create an index.php that redirects to the installer
            $redirect_script = "<?php
// Redirect to the WordPress installer if it exists
if (file_exists('./wp-install.php')) {
    header('Location: /wp-install.php');
    exit;
}

// Otherwise, load WordPress
require('./index.php');
";
            
            file_put_contents($document_root . '/index.php.redirect', $redirect_script);
            rename($document_root . '/index.php', $document_root . '/index.php.original');
            rename($document_root . '/index.php.redirect', $document_root . '/index.php');
        }
        
        // Update WordPress version in database
        $wp_version = '';
        if (file_exists($document_root . '/wp-includes/version.php')) {
            include($document_root . '/wp-includes/version.php');
            if (isset($wp_version)) {
                $db->update(
                    "UPDATE wordpress_sites SET wp_version = ? WHERE id = ?",
                    [$wp_version, $wp_id]
                );
            }
        }
        
        // Log the action
        log_action($user['id'], 'install_wordpress', 'Installed WordPress on domain: ' . $domain['domain_name']);
        
        // Commit transaction
        $db->commit();
        
        // Get the WordPress installation details
        $wp_site = $db->fetchOne(
            "SELECT ws.*, d.domain_name 
             FROM wordpress_sites ws
             JOIN domains d ON ws.domain_id = d.id
             WHERE ws.id = ?",
            [$wp_id]
        );
        
        // Format dates
        $wp_site['installed_at'] = date('Y-m-d H:i:s', strtotime($wp_site['installed_at']));
        if ($wp_site['updated_at']) {
            $wp_site['updated_at'] = date('Y-m-d H:i:s', strtotime($wp_site['updated_at']));
        }
        
        // Add admin URL and login credentials to response
        $wp_site['admin_url'] = 'http://' . $domain['domain_name'] . '/wp-admin/';
        $wp_site['admin_username'] = $wp_admin_user;
        $wp_site['admin_password'] = $wp_admin_password;
        
        return [
            'status' => 'success',
            'message' => 'WordPress installed successfully',
            'wordpress' => $wp_site
        ];
    } catch (Exception $e) {
        // Rollback transaction on error
        $db->rollback();
        api_error('Failed to install WordPress: ' . $e->getMessage(), 500);
    }
}